config/routes.rb
RamusPorady::Application.routes.draw do
  resources :ukols

  resources :funkces

  resources :jednanis

  resources :reports

  resources :poradas

root 'poradas#index'

end

app/models/porada.rb
class Porada < ActiveRecord::Base
  has_many :reports
  has_many :jednanis
  has_many :funkces
  has_many :ukols
  accepts_nested_attributes_for :reports, :allow_destroy => true
  accepts_nested_attributes_for :jednanis, :allow_destroy => true
  accepts_nested_attributes_for :funkces, :allow_destroy => true
  accepts_nested_attributes_for :ukols, :allow_destroy => true
end

app/controllers/poradas_controller.rb
class PoradasController < ApplicationController
  before_action :set_porada, only: [:show, :edit, :update, :destroy]

  # GET /poradas
  # GET /poradas.json
  def index
    @poradas = Porada.all
  end

  # GET /poradas/1
  # GET /poradas/1.json
  def show
  end

  # GET /poradas/new
  def new
    @porada = Porada.new
  end

  # GET /poradas/1/edit
  def edit
  end

  # POST /poradas
  # POST /poradas.json
  def create
    @porada = Porada.new(porada_params)

    respond_to do |format|
      if @porada.save
        format.html { redirect_to @porada, notice: 'Porada was successfully created.' }
        format.json { render action: 'show', status: :created, location: @porada }
      else
        format.html { render action: 'new' }
        format.json { render json: @porada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poradas/1
  # PATCH/PUT /poradas/1.json
  def update
    respond_to do |format|
      if @porada.update(porada_params)
        format.html { redirect_to @porada, notice: 'Porada was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @porada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poradas/1
  # DELETE /poradas/1.json
  def destroy
    @porada.destroy
    respond_to do |format|
      format.html { redirect_to poradas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_porada
      @porada = Porada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def porada_params
      params.require(:porada).permit(:datum, :cislo)
    end
end

app/helpers/poradas_helper.rb
module PoradasHelper
end

app/views/poradas/_form.html.erb
<%= form_for(@porada) do |f| %>
  <% if @porada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@porada.errors.count, "error") %> prohibited this porada from being saved:</h2>

      <ul>
      <% @porada.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label "Číslo porady" %><br>
    <%= f.number_field :cislo %>
  </div>

  <div class="field">
    <%= f.label :datum %><br>
    <%= f.date_select :datum %>
  </div>
  <div class="actions">
    <%= f.submit "Uložit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/poradas/edit.html.erb
<h1>Editing porada</h1>

<%= render 'form' %>

<%= link_to 'Show', @porada %> |
<%= link_to 'Back', poradas_path %>

app/views/poradas/index.html.erb
<h1>porady vedení</h1>

<div class="well well-lg" id="main_well">
	<table class="table table-condensed" id="main_table">
		<thead>
			<tr>
				<th>Číslo porady a datum</th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @poradas.each do |porada| %>

			<tr>
				<td><%= link_to porada.cislo.to_s + " // " + porada.datum.to_s, porada, class: "btn btn-default" %></td>
				<td><%= link_to 'Upravit', edit_porada_path(porada), :class => "btn btn-default" %>
					<%= link_to 'Smazat', porada, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>

			<% end %>
		</tbody>
	</table>
</div>

<br>

<%= link_to 'Vložit novou poradu', new_porada_path, :class => "btn btn-primary" %>

app/views/poradas/new.html.erb
<h1 class="nadpis">nová porada</h1>

<%= render 'form' %>

<%= link_to 'Zpět', poradas_path, :class => "btn btn-default" %>

app/views/poradas/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<div class="well well-lg">
	<h1> <%= "PV_" + @porada.cislo.to_s + " / " + @porada.datum.to_s %> </h1>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h2 class="panel-title">Reporty</h2>
		</div>
		<div class="panel-body">

			<% @porada.reports.each do |report| %>

			<ul class="list-group">
				<li class="list-group-item courier"><strong><%= Funkce.find(report.funkce_id).nazev_funkce %></li></strong>
				<li class="list-group-item"><%= report.obsah %></li>
			</ul>
			
			<% end %>
		</div>
	</div>


	
		<div class="panel panel-default">
		<div class="panel-heading">
			<h2 class="panel-title">Jednání</h2>
		</div>
		<div class="panel-body">

			<% @porada.jednanis.each do |jednani| %>

<!--<%= link_to 'Edit', edit_jednani_path(@jednani) %>-->

			<ul class="list-group">
				<li class="list-group-item courier"><strong><%= jednani.tema %></li></strong>
				<li class="list-group-item"><%= jednani.obsah %></li>
			</ul>

			<% end %>
		</div>
	</div>

	<%= link_to "Vložit nový report", new_report_path(porada_id: @porada.id), :class => "btn btn-primary" %>

	<%= link_to "Vložit nové jednání", new_jednani_path(porada_id: @porada.id), :class => "btn btn-primary" %>

	<%= link_to 'Upravit poradu', edit_porada_path(@porada), :class => "btn btn-default" %> |
	<%= link_to 'Zpět', poradas_path, :class => "btn btn-default" %>

</div>