config/routes.rb
RamusPorady::Application.routes.draw do
  resources :ukols

  resources :funkces

  resources :jednanis

  resources :reports

  resources :poradas

root 'poradas#index'

end

app/models/jednani.rb
class Jednani < ActiveRecord::Base
  belongs_to :porada
end

app/controllers/jednanis_controller.rb
class JednanisController < ApplicationController
  before_action :set_jednani, only: [:show, :edit, :update, :destroy]

  # GET /jednanis
  # GET /jednanis.json
  def index
    @jednanis = Jednani.all
  end

  # GET /jednanis/1
  # GET /jednanis/1.json
  def show
  end

  # GET /jednanis/new
  def new
    @jednani = Jednani.new
    @porada_id = params[:porada_id]
  end

  # GET /jednanis/1/edit
  def edit
  end

  # POST /jednanis
  # POST /jednanis.json
  def create
    @jednani = Jednani.new(jednani_params)

    respond_to do |format|
      if @jednani.save
        format.html { redirect_to @jednani, notice: 'Jednani was successfully created.' }
        format.json { render action: 'show', status: :created, location: @jednani }
      else
        format.html { render action: 'new' }
        format.json { render json: @jednani.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jednanis/1
  # PATCH/PUT /jednanis/1.json
  def update
    respond_to do |format|
      if @jednani.update(jednani_params)
        format.html { redirect_to @jednani, notice: 'Jednani was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @jednani.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jednanis/1
  # DELETE /jednanis/1.json
  def destroy
    @jednani.destroy
    respond_to do |format|
      format.html { redirect_to jednanis_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jednani
      @jednani = Jednani.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jednani_params
      params.require(:jednani).permit(:porada_id, :tema, :obsah)
    end
end

app/helpers/jednanis_helper.rb
module JednanisHelper
end

app/views/jednanis/_form.html.erb
<%= form_for(@jednani) do |f| %>
  <% if @jednani.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jednani.errors.count, "error") %> prohibited this jednani from being saved:</h2>

      <ul>
      <% @jednani.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :porada_id, :value => @porada_id %>
  </div>
  <div class="field">
    <%= f.label :tema %><br>
    <%= f.text_field :tema %>
  </div>
  <div class="field">
    <%= f.label :obsah %><br>
    <%= f.text_area :obsah %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jednanis/edit.html.erb
<h1>Editing jednani</h1>

<%= render 'form' %>

<%= link_to 'Show', @jednani %> |
<%= link_to 'Back', jednanis_path %>

app/views/jednanis/index.html.erb
<h1>Listing jednanis</h1>

<table>
  <thead>
    <tr>
      <th>Porada</th>
      <th>Tema</th>
      <th>Obsah</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jednanis.each do |jednani| %>
      <tr>
        <td><%= jednani.porada_id %></td>
        <td><%= jednani.tema %></td>
        <td><%= jednani.obsah %></td>
        <td><%= link_to 'Show', jednani %></td>
        <td><%= link_to 'Edit', edit_jednani_path(jednani) %></td>
        <td><%= link_to 'Destroy', jednani, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jednani', new_jednani_path %>

app/views/jednanis/new.html.erb
<h1>New jednani</h1>

<%= render 'form' %>

<%= link_to 'Back', jednanis_path %>

app/views/jednanis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Porada:</strong>
  <%= @jednani.porada_id %>
</p>

<p>
  <strong>Tema:</strong>
  <%= @jednani.tema %>
</p>

<p>
  <strong>Obsah:</strong>
  <%= @jednani.obsah %>
</p>

<%= link_to 'Upravit', edit_jednani_path(@jednani) %> |
<%= link_to 'Back', porada_path(@jednani.porada_id) %>