config/routes.rb
RamusPorady::Application.routes.draw do
  resources :ukols

  resources :funkces

  resources :jednanis

  resources :reports

  resources :poradas

root 'poradas#index'

end

app/models/ukol.rb
class Ukol < ActiveRecord::Base
  belongs_to :porada
  belongs_to :funkce
end

app/controllers/ukols_controller.rb
class UkolsController < ApplicationController
  before_action :set_ukol, only: [:show, :edit, :update, :destroy]

  # GET /ukols
  # GET /ukols.json
  def index
    @ukols = Ukol.all
  end

  # GET /ukols/1
  # GET /ukols/1.json
  def show
  end

  # GET /ukols/new
  def new
    @ukol = Ukol.new
  end

  # GET /ukols/1/edit
  def edit
  end

  # POST /ukols
  # POST /ukols.json
  def create
    @ukol = Ukol.new(ukol_params)

    respond_to do |format|
      if @ukol.save
        format.html { redirect_to @ukol, notice: 'Ukol was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ukol }
      else
        format.html { render action: 'new' }
        format.json { render json: @ukol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ukols/1
  # PATCH/PUT /ukols/1.json
  def update
    respond_to do |format|
      if @ukol.update(ukol_params)
        format.html { redirect_to @ukol, notice: 'Ukol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ukol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ukols/1
  # DELETE /ukols/1.json
  def destroy
    @ukol.destroy
    respond_to do |format|
      format.html { redirect_to ukols_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ukol
      @ukol = Ukol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ukol_params
      params.require(:ukol).permit(:funkce_id, :porada_id, :splneno, :deadline, :obsah)
    end
end

app/helpers/ukols_helper.rb
module UkolsHelper
end

app/views/ukols/_form.html.erb
<%= form_for(@ukol) do |f| %>
  <% if @ukol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ukol.errors.count, "error") %> prohibited this ukol from being saved:</h2>

      <ul>
      <% @ukol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :funkce_id %><br>
    <%= f.number_field :funkce_id %>
  </div>
  <div class="field">
    <%= f.label :porada_id %><br>
    <%= f.number_field :porada_id %>
  </div>
  <div class="field">
    <%= f.label :splneno %><br>
    <%= f.check_box :splneno %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :obsah %><br>
    <%= f.text_area :obsah %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ukols/edit.html.erb
<h1>Editing ukol</h1>

<%= render 'form' %>

<%= link_to 'Show', @ukol %> |
<%= link_to 'Back', ukols_path %>

app/views/ukols/index.html.erb
<h1>Listing ukols</h1>

<table>
  <thead>
    <tr>
      <th>Funkce</th>
      <th>Porada</th>
      <th>Splneno</th>
      <th>Deadline</th>
      <th>Obsah</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ukols.each do |ukol| %>
      <tr>
        <td><%= ukol.funkce_id %></td>
        <td><%= ukol.porada_id %></td>
        <td><%= ukol.splneno %></td>
        <td><%= ukol.deadline %></td>
        <td><%= ukol.obsah %></td>
        <td><%= link_to 'Show', ukol %></td>
        <td><%= link_to 'Edit', edit_ukol_path(ukol) %></td>
        <td><%= link_to 'Destroy', ukol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ukol', new_ukol_path %>

app/views/ukols/new.html.erb
<h1>New ukol</h1>

<%= render 'form' %>

<%= link_to 'Back', ukols_path %>

app/views/ukols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Funkce:</strong>
  <%= @ukol.funkce_id %>
</p>

<p>
  <strong>Porada:</strong>
  <%= @ukol.porada_id %>
</p>

<p>
  <strong>Splneno:</strong>
  <%= @ukol.splneno %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @ukol.deadline %>
</p>

<p>
  <strong>Obsah:</strong>
  <%= @ukol.obsah %>
</p>

<%= link_to 'Edit', edit_ukol_path(@ukol) %> |
<%= link_to 'Back', ukols_path %>